//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Construction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Change_Order = new HashSet<Change_Order>();
            this.DailyItems = new HashSet<DailyItem>();
        }
    
        public int ID { get; set; }
        public int JobID { get; set; }
        public string Description { get; set; }
        public string UnitType { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> InitialQuantity { get; set; }
        public int ItemNumber { get; set; }
        public Nullable<double> SubContractorQuantity { get; set; }
        public Nullable<int> SubContractorId { get; set; }
        public Nullable<double> SubUnit_price { get; set; }
    
        public virtual ICollection<Change_Order> Change_Order { get; set; }
        public virtual ICollection<DailyItem> DailyItems { get; set; }
        public virtual Job Job { get; set; }
    }
}
