//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Construction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobData
    {
        public int ID { get; set; }
        public int JobID { get; set; }
        public System.DateTime Date { get; set; }
        public string Weather { get; set; }
        public Nullable<double> Temperature { get; set; }
        public string Shift { get; set; }
        public string Estimate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ContractorId { get; set; }
        public string EntryType { get; set; }
    }
}
