//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Construction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public string Clientname { get; set; }
        public Nullable<int> FromUser { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<double> units { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> Jobid { get; set; }
        public Nullable<int> Itemid { get; set; }
    }
}
