//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Construction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblworkforce
    {
        public int id { get; set; }
        public string Workforcename { get; set; }
        public Nullable<int> numberof { get; set; }
        public Nullable<int> JobDataid { get; set; }
    }
}
